#pragma once

#include <chrono>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace pmlmq {

/// Configuration for the aging mechanism that promotes long-waiting messages
/// to a higher-priority level to prevent starvation.
struct AgingConfig {
    /// How long a message must wait before being promoted one level up.
    std::chrono::milliseconds threshold{5000};
    /// How often the aging background thread runs its scan.
    std::chrono::milliseconds interval{500};
};

/// A single message flowing through the PMLMQ system.
///
/// Priority is an integer in [0, num_levels), where 0 is the highest priority.
/// The Proxy sets arrival_time and id on submission; enqueue_time is updated
/// each time the message is placed (or re-placed) into a queue level.
struct Message {
    /// Unique message identifier — generated by Proxy::generate_id() if empty.
    std::string id;

    /// Opaque message payload.
    std::vector<uint8_t> payload;

    /// Current priority level: 0 = highest. Modified by aging promotion.
    uint8_t priority{1};

    /// Priority at original submission — used when re-queuing after nack.
    uint8_t original_priority{1};

    /// Wall-clock time when the message first entered the system (set by Proxy).
    std::chrono::steady_clock::time_point arrival_time{};

    /// Time when the message was last placed into a queue level.
    /// Reset on aging promotion so the threshold is relative to queue entry.
    std::chrono::steady_clock::time_point enqueue_time{};

    /// Maximum time-to-live from arrival_time. Zero means no expiry.
    std::chrono::milliseconds ttl{0};

    /// Number of times this message has been nack'd.
    uint32_t retry_count{0};

    /// Maximum nack retries before the message is sent to the DLQ.
    uint32_t max_retries{3};

    /// Arbitrary key-value metadata for routing hints and feature extraction.
    std::unordered_map<std::string, std::string> headers;

    /// Returns true if the message has exceeded its TTL.
    [[nodiscard]] bool is_expired() const noexcept {
        if (ttl.count() == 0) return false;
        return (std::chrono::steady_clock::now() - arrival_time) >= ttl;
    }
};

/// Reason a message was sent to the Dead Letter Queue.
enum class DLQReason : uint8_t {
    MAX_RETRIES_EXCEEDED,
    TTL_EXPIRED,
    PROCESSING_ERROR,
};

/// A message that has been moved to the Dead Letter Queue, together with
/// the reason and a human-readable description of the failure.
struct DLQEntry {
    Message message;
    DLQReason reason;
    std::chrono::steady_clock::time_point dlq_time{};
    std::string details;
};

} // namespace pmlmq
