#pragma once

#include "proxy/proxy.hpp"
#include "queue/dead_letter_queue.hpp"
#include "queue/message.hpp"
#include "queue/multi_level_queue.hpp"
#include "ml/routing_context.hpp"
#include "ml/feedback_writer.hpp"
#include "ml/predictive_routing.hpp"

// Generated by protoc — present only after cmake build.
#include <harbinger.grpc.pb.h>

#include <array>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <list>
#include <map>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace harbinger {

/// System-wide server configuration.
struct HarbingerConfig {
    /// Number of priority queue levels; level 0 is highest.
    uint8_t num_levels{3};

    /// Aging policy; nullopt selects strict-priority mode with no aging thread.
    std::optional<AgingConfig> aging{std::nullopt};

    /// Delivery attempts per message before it moves to the DLQ.
    uint32_t default_max_retries{3};

    /// Default TTL from arrival_time; zero disables expiry.
    std::chrono::milliseconds default_ttl{0};

    /// Static ingress priority; must be less than num_levels.
    uint8_t default_priority{1};

    /// Upper bound on how long a Pull handler blocks waiting for a message.
    std::chrono::milliseconds max_pull_wait{5000};

    /// Queue TTL sweep interval; zero disables only background queue TTL cleanup.
    std::chrono::milliseconds ttl_sweep_interval{100};
    /// Fixed delivery lease; handlers must finish before it expires.
    std::chrono::milliseconds delivery_lease{30000};
    /// Cadence for bounded lease reclamation and completion-history cleanup.
    std::chrono::milliseconds lease_sweep_interval{100};
    /// Maximum completion-history age from settlement/reclamation, subject to capacity.
    std::chrono::milliseconds completion_retention{60000};
    /// Maximum retained attempt outcomes; capacity eviction can shorten retention.
    std::size_t completion_cache_max_entries{10000};
    /// Maximum entries processed per queue TTL, lease, or history maintenance batch.
    std::size_t maintenance_batch_size{256};
    /// Opt-in bounded ingress snapshots for static-mode Phase 2 data collection.
    std::optional<ml::IngressFeatureConfig> ingress_features{};
    /// Optional asynchronous feedback; requires explicit ingress feature configuration.
    std::optional<ml::FeedbackConfig> feedback{};
    /// Opt-in in-process per-key prediction (shadow or predictive); absent keeps static routing with no predictor.
    std::optional<ml::PredictiveRoutingConfig> predictive_routing{};
#ifdef HARBINGER_BENCHMARK_SUPPORT
    /// Evaluation-only options, absent from the ordinary broker build.
    std::optional<benchmark::Options> benchmark_options{};
#endif
};

/// Thread-safe gRPC broker with attempt-fenced, at-least-once delivery recovery.
class HarbingerService final : public harbinger_rpc::Broker::Service {
public:
    /// Validate configuration and start queue/delivery maintenance.
    explicit HarbingerService(HarbingerConfig config = {});

    // Non-copyable, non-movable (owns threads).
    HarbingerService(const HarbingerService&) = delete;
    HarbingerService& operator=(const HarbingerService&) = delete;

    /// Join maintenance before releasing queue resources.
    ~HarbingerService();

    /// Register a producer and assign its ID.
    grpc::Status RegisterProducer(grpc::ServerContext* ctx,
                                  const harbinger_rpc::RegisterProducerRequest* req,
                                  harbinger_rpc::RegisterProducerResponse* resp) override;

    /// Accept a producer payload into the queue.
    grpc::Status Submit(grpc::ServerContext* ctx,
                        const harbinger_rpc::SubmitRequest* req,
                        harbinger_rpc::SubmitResponse* resp) override;

    /// Register a consumer and assign its ID.
    grpc::Status RegisterConsumer(grpc::ServerContext* ctx,
                                  const harbinger_rpc::RegisterConsumerRequest* req,
                                  harbinger_rpc::RegisterConsumerResponse* resp) override;

    /// Wait for a live message and install a fresh attempt token and fixed lease.
    grpc::Status Pull(grpc::ServerContext* ctx,
                      const harbinger_rpc::PullRequest* req,
                      harbinger_rpc::PullResponse* resp) override;

    /// Settle a valid attempt successfully, or replay its retained Ack outcome.
    grpc::Status Ack(grpc::ServerContext* ctx,
                     const harbinger_rpc::AckRequest* req,
                     harbinger_rpc::AckResponse* resp) override;

    /// Retry/DLQ a valid attempt once, or replay its retained Nack outcome.
    grpc::Status Nack(grpc::ServerContext* ctx,
                      const harbinger_rpc::NackRequest* req,
                      harbinger_rpc::NackResponse* resp) override;

    /// Inspect retained DLQ entries without removing them.
    grpc::Status InspectDlq(grpc::ServerContext* ctx,
                            const harbinger_rpc::InspectDlqRequest* req,
                            harbinger_rpc::InspectDlqResponse* resp) override;

    // Observability
    /// Queued (not in-flight, not DLQ) message count.
    [[nodiscard]] std::size_t queue_size() const { return queue_.size(); }
    /// Retained DLQ entry count.
    [[nodiscard]] std::size_t dlq_size()   const { return dlq_.size();   }
    /// Copy a page of DLQ entries without removing them.
    [[nodiscard]] std::vector<DLQEntry> dlq_snapshot(
        std::size_t offset, std::size_t limit) const {
        return dlq_.snapshot(offset, limit);
    }
    /// Messages pulled but not yet acked/nacked.
    [[nodiscard]] std::size_t in_flight_count() const;
    /// Approximate bounded feedback counters; disabled collection returns zero stats.
    [[nodiscard]] ml::FeedbackStats feedback_stats() const noexcept;
    /// Bounded routing, learning, drift and snapshot counters; disabled prediction returns enabled=false.
    [[nodiscard]] ml::RoutingStats routing_stats() const;
    /// Write the predictor snapshot now if one is configured; returns false (and counts a failure) on error.
    bool save_predictor_snapshot() noexcept;
#ifdef HARBINGER_BENCHMARK_SUPPORT
    /// Quiesced benchmark shutdown: join maintenance and seal feedback before auditing it.
    void benchmark_close_feedback();
    [[nodiscard]] std::string benchmark_instance() const {
        return feedback_writer_ ? feedback_writer_->instance_id() : "telemetry-off";
    }
#endif

private:
    friend struct BrokerTestAccess;
    using Clock = std::chrono::steady_clock;
    using DeadlineIndex = std::multimap<Clock::time_point, std::string>;
    enum class Settlement { Ack, Nack, Expired };
    struct Completion {
        std::string message_id;
        std::string token;
        std::string owner;
        Settlement kind;
        Clock::time_point time;
    };
    using CompletionList = std::list<Completion>;
    /// Learning work captured under the settlement lock and applied to the predictor after it is released.
    struct PredictorUpdate {
        std::string key;
        std::optional<std::string> parent;
        std::optional<double> duration_ms;
        bool censored{false};
        std::optional<double> predicted_ms;
        std::optional<uint8_t> predicted_bucket;
    };
    grpc::Status settle(const std::string& owner, const std::string& id,
                        const std::string& token, Settlement kind, const std::string& reason,
                        int64_t processing_time_ms);
    std::optional<ml::FeedbackEvent> finish_locked(const std::string& id, Settlement kind,
                                                 const std::string& reason,
                                                 std::optional<int64_t> measurement = std::nullopt,
                                                 std::optional<PredictorUpdate>* update = nullptr);
    /// Feed a captured outcome to the predictor; never called with broker locks held.
    void learn(const PredictorUpdate& update) noexcept;
    /// Predict at ingress, fill the routing context and return the chosen priority.
    uint8_t predict_route(Message& msg, ml::RoutingContext& context) noexcept;
    std::optional<ml::FeedbackEvent> capture_event(const Message& message, ml::FeedbackTrigger trigger) noexcept;
    void publish_event(const std::optional<ml::FeedbackEvent>& event) noexcept;
    void maintain_deliveries();
    void prune_completions_locked(std::size_t budget);
    /// Assign routing context and enqueue an accepted message.
    void route_message(Message msg);

    /// Check producer registration.
    [[nodiscard]] bool is_registered_producer(const std::string& id) const;
    /// Check consumer registration.
    [[nodiscard]] bool is_registered_consumer(const std::string& id) const;

    HarbingerConfig     config_;
    std::optional<ml::FeatureExtractor> feature_extractor_;
    std::unique_ptr<ml::PerKeyPredictor> predictor_;
    std::string snapshot_context_;
    /// Lock-free counters behind routing_stats(); the drift window has its own small mutex.
    struct RoutingCounters {
        std::atomic<uint64_t> lookups{0}, routed{0}, parent_fallbacks{0}, latency_total{0}, latency_max{0};
        std::array<std::atomic<uint64_t>, ml::kPredictionStatusCount> outcomes{};
        std::array<std::atomic<uint64_t>, ml::kLatencyBuckets> latency{};
        std::atomic<uint64_t> learned{0}, learn_rejected{0}, censored{0};
        std::atomic<uint64_t> snapshot_saves{0}, snapshot_failures{0};
        mutable std::mutex drift_mutex;
        uint64_t scored{0}, matches{0}, drift_alerts{0};
        double error_ewma{0.0};
        std::array<bool, 512> window{};
        std::size_t window_next{0}, window_size{0}, window_hits{0};
        bool drift_latched{false};
        bool snapshot_loaded{false};
        std::string snapshot_status{"none"};
    };
    mutable RoutingCounters routing_;
    std::unique_ptr<ml::FeedbackWriter> feedback_writer_;
    MultiLevelQueue queue_;
    DeadLetterQueue dlq_;
    Proxy           proxy_;

    // In-flight: pulled but not yet ack'd/nack'd.
    struct InFlightEntry {
        Message     message;
        std::string consumer_id;
        std::chrono::steady_clock::time_point pull_time;
        std::string attempt_token;
        DeadlineIndex::iterator deadline;
        uint64_t attempt_id{0};
    };
    mutable std::mutex in_flight_mutex_;
    std::unordered_map<std::string, InFlightEntry> in_flight_;
    DeadlineIndex deadlines_;
    const std::string instance_token_;
    CompletionList completions_;
    std::unordered_map<std::string, CompletionList::iterator> completed_;

    // Registered clients
    mutable std::mutex                producers_mutex_;
    std::unordered_set<std::string>   registered_producers_;
    std::atomic<uint64_t>             producer_counter_{0};

    mutable std::mutex                consumers_mutex_;
    std::unordered_set<std::string>   registered_consumers_;
    std::atomic<uint64_t>             consumer_counter_{0};

    // Background maintenance (declared last: joined first on destruction,
    // before the queue shuts down).
    std::atomic<bool> stop_sweeper_{false};
    std::mutex        sweeper_mutex_;
    std::condition_variable sweeper_cv_;
    std::thread       sweeper_thread_;

    /// Independently schedule bounded lease, TTL, and completion cleanup.
    void run_maintenance();

    /// Move already-swept messages into the DLQ with a TTL_EXPIRED reason.
    void dlq_swept(std::vector<Message> expired, std::string details);
};

} // namespace harbinger
