#pragma once

#include "proxy/proxy.hpp"
#include "queue/dead_letter_queue.hpp"
#include "queue/message.hpp"
#include "queue/multi_level_queue.hpp"

// Generated by protoc — present only after cmake build.
#include <pmlmq.grpc.pb.h>

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace pmlmq {

/// System-wide server configuration.
struct PMLMQConfig {
    /// Number of priority queue levels; level 0 is highest.
    uint8_t num_levels{3};

    /// Aging policy; nullopt selects strict-priority mode with no aging thread.
    std::optional<AgingConfig> aging{std::nullopt};

    /// Delivery attempts per message before it moves to the DLQ.
    uint32_t default_max_retries{3};

    /// Default TTL from arrival_time; zero disables expiry.
    std::chrono::milliseconds default_ttl{0};

    /// Ingress priority for every message (static today, ML-predicted later).
    /// Must be < num_levels or the service constructor throws.
    uint8_t default_priority{1};

    /// Upper bound on how long a Pull handler blocks waiting for a message.
    std::chrono::milliseconds max_pull_wait{5000};

    /// Interval of the background TTL sweeper that reclaims expired messages
    /// nobody pulls; zero disables the sweeper (Pull still expires on scan).
    std::chrono::milliseconds ttl_sweep_interval{100};
};

/// gRPC Broker service and system orchestrator.
/// Owns the multi-level queue, DLQ, proxy, in-flight map, and client
/// registries. Decides which message each Pull receives. Thread-safe:
/// gRPC dispatches RPC handlers from a thread pool.
class PMLMQService final : public pmlmq_rpc::Broker::Service {
public:
    /// Build the broker from config.
    /// @param config Levels, aging, retries, TTL, ingress priority, pull cap.
    /// @side_effects Constructs the queue, DLQ, and proxy wired to route_message.
    /// @throws std::invalid_argument if default_priority >= num_levels.
    explicit PMLMQService(PMLMQConfig config = {});

    // Non-copyable, non-movable (owns threads).
    PMLMQService(const PMLMQService&) = delete;
    PMLMQService& operator=(const PMLMQService&) = delete;

    /// Stop the TTL sweeper and release queue resources.
    /// @side_effects Signals the sweeper to stop and joins it before the
    ///   queue shuts down.
    ~PMLMQService();

    /// Register a producer and assign its ID.
    /// @param req Empty registration request (reserved for future fields).
    /// @param resp Receives producer_id ("producer-<counter>").
    /// @return OK; always succeeds.
    /// @side_effects Inserts the new ID into the producer registry.
    grpc::Status RegisterProducer(grpc::ServerContext* ctx,
                                  const pmlmq_rpc::RegisterProducerRequest* req,
                                  pmlmq_rpc::RegisterProducerResponse* resp) override;

    /// Accept a producer payload into the queue.
    /// @param req Carries producer_id, payload bytes, and headers.
    /// @param resp Receives the broker-assigned message_id.
    /// @return OK on enqueue; PERMISSION_DENIED for an unknown producer.
    /// @side_effects Stamps ID/arrival_time via Proxy and enqueues the message.
    grpc::Status Submit(grpc::ServerContext* ctx,
                        const pmlmq_rpc::SubmitRequest* req,
                        pmlmq_rpc::SubmitResponse* resp) override;

    /// Register a consumer and assign its ID.
    /// @param req Empty registration request (reserved for future fields).
    /// @param resp Receives consumer_id ("consumer-<counter>").
    /// @return OK; always succeeds.
    /// @side_effects Inserts the new ID into the consumer registry.
    grpc::Status RegisterConsumer(grpc::ServerContext* ctx,
                                  const pmlmq_rpc::RegisterConsumerRequest* req,
                                  pmlmq_rpc::RegisterConsumerResponse* resp) override;

    /// Block until a message is available or the timeout elapses.
    /// @param req Carries consumer_id and timeout_ms (0 selects the server default).
    /// @param resp Receives timed_out=true when nothing arrived, else the
    ///   highest-priority message with its ID, payload, and headers.
    /// @return OK with a message or timed_out; PERMISSION_DENIED for an
    ///   unknown consumer; CANCELLED when the client cancels mid-wait.
    /// @side_effects Caps the wait at max_pull_wait, polls in 100 ms chunks,
    ///   DLQs TTL-expired messages while scanning, and records dispatched
    ///   messages in the in-flight map under the pulling consumer.
    grpc::Status Pull(grpc::ServerContext* ctx,
                      const pmlmq_rpc::PullRequest* req,
                      pmlmq_rpc::PullResponse* resp) override;

    /// Confirm successful processing and release the message.
    /// @param req Carries consumer_id, message_id, and measured processing_time_ms.
    /// @return OK on delete; PERMISSION_DENIED for unknown consumer or wrong
    ///   owner; NOT_FOUND when the message is not in flight.
    /// @side_effects Removes the entry from the in-flight map. When the
    ///   message expired mid-processing it is also retained in the DLQ as
    ///   TTL_EXPIRED; the caller still sees OK.
    grpc::Status Ack(grpc::ServerContext* ctx,
                     const pmlmq_rpc::AckRequest* req,
                     pmlmq_rpc::AckResponse* resp) override;

    /// Report failed processing for retry or DLQ.
    /// @param req Carries consumer_id, message_id, processing_time_ms, and reason.
    /// @return OK on re-queue/DLQ; PERMISSION_DENIED for unknown consumer or
    ///   wrong owner; NOT_FOUND when the message is not in flight.
    /// @side_effects Removes the in-flight entry. An already-expired message
    ///   DLQs as TTL_EXPIRED without touching retry_count; otherwise
    ///   increments retry_count, then re-queues at original_priority or DLQs
    ///   on max-retries with the caller reason appended to the DLQ details.
    grpc::Status Nack(grpc::ServerContext* ctx,
                      const pmlmq_rpc::NackRequest* req,
                      pmlmq_rpc::NackResponse* resp) override;

    /// Inspect retained DLQ entries without removing them.
    /// @param req Carries limit (<=0 selects 10, capped at 100) and offset
    ///   (negative clamps to 0) for FIFO pagination.
    /// @param resp Receives up to limit entries plus the total DLQ depth.
    /// @return OK; no registration required (operator endpoint).
    /// @side_effects None; takes a consistent snapshot under the DLQ lock.
    grpc::Status InspectDlq(grpc::ServerContext* ctx,
                            const pmlmq_rpc::InspectDlqRequest* req,
                            pmlmq_rpc::InspectDlqResponse* resp) override;

    // Observability
    /// Queued (not in-flight, not DLQ) message count.
    /// @return Total size across all queue levels.
    [[nodiscard]] std::size_t queue_size() const { return queue_.size(); }
    /// Retained DLQ entry count.
    /// @return Current DLQ depth.
    [[nodiscard]] std::size_t dlq_size()   const { return dlq_.size();   }
    /// Copy a page of DLQ entries without removing them.
    /// @return Up to limit entries starting at offset, in FIFO order.
    [[nodiscard]] std::vector<DLQEntry> dlq_snapshot(
        std::size_t offset, std::size_t limit) const {
        return dlq_.snapshot(offset, limit);
    }
    /// Messages pulled but not yet acked/nacked.
    /// @return Current in-flight map size.
    [[nodiscard]] std::size_t in_flight_count() const;

private:
    /// Assign routing context and enqueue an accepted message.
    /// @param msg Stamped message from the Proxy sink.
    /// @side_effects Sets priority/original_priority from config, applies
    ///   default retries/TTL when unset, and enqueues. Future ML classifier
    ///   injection point.
    void route_message(Message msg);

    /// Check producer registration.
    /// @param id Producer ID to look up.
    /// @return True when the ID is registered.
    [[nodiscard]] bool is_registered_producer(const std::string& id) const;
    /// Check consumer registration.
    /// @param id Consumer ID to look up.
    /// @return True when the ID is registered.
    [[nodiscard]] bool is_registered_consumer(const std::string& id) const;

    PMLMQConfig     config_;
    MultiLevelQueue queue_;
    DeadLetterQueue dlq_;
    Proxy           proxy_;

    // In-flight: pulled but not yet ack'd/nack'd.
    struct InFlightEntry {
        Message     message;
        std::string consumer_id;
        std::chrono::steady_clock::time_point pull_time;
    };
    mutable std::mutex in_flight_mutex_;
    std::unordered_map<std::string, InFlightEntry> in_flight_;

    // Registered clients
    mutable std::mutex                producers_mutex_;
    std::unordered_set<std::string>   registered_producers_;
    std::atomic<uint64_t>             producer_counter_{0};

    mutable std::mutex                consumers_mutex_;
    std::unordered_set<std::string>   registered_consumers_;
    std::atomic<uint64_t>             consumer_counter_{0};

    // Background TTL sweeper (declared last: joined first on destruction,
    // before the queue shuts down).
    std::atomic<bool> stop_sweeper_{false};
    std::mutex        sweeper_mutex_;
    std::condition_variable sweeper_cv_;
    std::thread       sweeper_thread_;

    /// Periodically move TTL-expired messages from the queue to the DLQ.
    /// @side_effects Sweeps every ttl_sweep_interval until stop_sweeper_.
    void run_ttl_sweeper();

    /// Move already-swept messages into the DLQ with a TTL_EXPIRED reason.
    /// @param expired Messages removed by MultiLevelQueue::sweep_expired.
    /// @param details Human-readable context stored on each DLQ entry.
    /// @side_effects Pushes one DLQ entry per message.
    void dlq_swept(std::vector<Message> expired, std::string details);
};

} // namespace pmlmq
