#pragma once

#include "proxy/proxy.hpp"
#include "queue/dead_letter_queue.hpp"
#include "queue/message.hpp"
#include "queue/multi_level_queue.hpp"

// Generated by protoc — present only after cmake build.
#include <pmlmq.grpc.pb.h>

#include <atomic>
#include <chrono>
#include <mutex>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>

namespace pmlmq {

/// System-wide server configuration.
///
///     PMLMQService service{ PMLMQConfig{
///         .num_levels          = 3,
///         .aging               = AgingConfig{ .threshold = 2s, .interval = 500ms },
///         .default_max_retries = 5,
///         .default_priority    = 1,   // MEDIUM
///     }};
struct PMLMQConfig {
    /// Number of priority queue levels. Level 0 is highest.
    uint8_t num_levels{3};

    /// Optional aging: background thread promotes long-waiting messages toward
    /// level 0 so lower-priority queues are never permanently starved.
    std::optional<AgingConfig> aging{std::nullopt};

    /// Default delivery attempts before a message is moved to the DLQ.
    uint32_t default_max_retries{3};

    /// Default TTL from arrival. Zero means no expiry.
    std::chrono::milliseconds default_ttl{0};

    /// Priority assigned to every message at ingress.
    /// Phase 1: static. Phase 2: overridden by the ML classifier.
    uint8_t default_priority{1};

    /// Maximum time the server will block inside a Pull() handler waiting for
    /// a message. The consumer's requested timeout_ms is capped to this value.
    std::chrono::milliseconds max_pull_wait{5000};
};

/// gRPC Broker service implementation and system orchestrator.
///
/// Owns the multi-level queue, DLQ, and proxy. All coordination happens here:
/// producers register and submit messages; consumers register and pull messages;
/// PMLMQ decides which message each pull receives (consumers are tier-blind).
///
/// Thread-safe: gRPC calls concurrent RPC handlers from a thread pool.
class PMLMQService final : public pmlmq_rpc::Broker::Service {
public:
    explicit PMLMQService(PMLMQConfig config = {});

    // Non-copyable, non-movable (owns live threads via MultiLevelQueue aging).
    PMLMQService(const PMLMQService&) = delete;
    PMLMQService& operator=(const PMLMQService&) = delete;

    // ── Producer RPCs ────────────────────────────────────────────────────────

    grpc::Status RegisterProducer(grpc::ServerContext* ctx,
                                  const pmlmq_rpc::RegisterProducerRequest* req,
                                  pmlmq_rpc::RegisterProducerResponse* resp) override;

    grpc::Status Submit(grpc::ServerContext* ctx,
                        const pmlmq_rpc::SubmitRequest* req,
                        pmlmq_rpc::SubmitResponse* resp) override;

    // ── Consumer RPCs ────────────────────────────────────────────────────────

    grpc::Status RegisterConsumer(grpc::ServerContext* ctx,
                                  const pmlmq_rpc::RegisterConsumerRequest* req,
                                  pmlmq_rpc::RegisterConsumerResponse* resp) override;

    /// Block until a message is available or the timeout elapses.
    /// PMLMQ picks the highest-priority message — consumers are tier-blind.
    grpc::Status Pull(grpc::ServerContext* ctx,
                      const pmlmq_rpc::PullRequest* req,
                      pmlmq_rpc::PullResponse* resp) override;

    grpc::Status Ack(grpc::ServerContext* ctx,
                     const pmlmq_rpc::AckRequest* req,
                     pmlmq_rpc::AckResponse* resp) override;

    grpc::Status Nack(grpc::ServerContext* ctx,
                      const pmlmq_rpc::NackRequest* req,
                      pmlmq_rpc::NackResponse* resp) override;

    // ── Observability ────────────────────────────────────────────────────────

    [[nodiscard]] std::size_t queue_size() const { return queue_.size(); }
    [[nodiscard]] std::size_t dlq_size()   const { return dlq_.size();   }
    [[nodiscard]] std::size_t in_flight_count() const;

private:
    /// Assigns system context (priority, TTL, retries) and enqueues.
    /// Called by the Proxy's MessageSink on every Submit RPC.
    /// Phase 2: this is where the ML classifier call will be injected.
    void route_message(Message msg);

    [[nodiscard]] bool is_registered_producer(const std::string& id) const;
    [[nodiscard]] bool is_registered_consumer(const std::string& id) const;

    PMLMQConfig     config_;
    MultiLevelQueue queue_;
    DeadLetterQueue dlq_;
    Proxy           proxy_;

    // ── In-flight tracking ───────────────────────────────────────────────────
    // Messages pulled by a consumer but not yet ack'd or nack'd.
    struct InFlightEntry {
        Message     message;
        std::string consumer_id;
        std::chrono::steady_clock::time_point pull_time;
    };
    mutable std::mutex in_flight_mutex_;
    std::unordered_map<std::string, InFlightEntry> in_flight_;

    // ── Registered clients ───────────────────────────────────────────────────
    mutable std::mutex                producers_mutex_;
    std::unordered_set<std::string>   registered_producers_;
    std::atomic<uint64_t>             producer_counter_{0};

    mutable std::mutex                consumers_mutex_;
    std::unordered_set<std::string>   registered_consumers_;
    std::atomic<uint64_t>             consumer_counter_{0};
};

} // namespace pmlmq
